fix block alignment

diff --git a/.github/workflows/test-de-id.yaml b/.github/workflows/test-de-id.yaml
--- a/.github/workflows/test-de-id.yaml
+++ b/.github/workflows/test-de-id.yaml
@@ -16,10 +16,11 @@ jobs:
     needs: build
     runs-on: ubuntu-latest
     steps:
-      run: |
-        echo "Cobertura minina: 80%"
-        echo "Cobertura obtida:  ${{ needs.build.outputs.test-cobertura }}%"
-        if (( ${{ needs.build.outputs.test-cobertura }} < 80 )) ; then 
-          echo "::error::Build reprovado por cobertura baixa"
-          exit 1
-        fi
+      - name
+        run: |
+          echo "Cobertura minina: 80%"
+          echo "Cobertura obtida:  ${{ needs.build.outputs.test-cobertura }}%"
+          if (( ${{ needs.build.outputs.test-cobertura }} < 80 )) ; then 
+            echo "::error::Build reprovado por cobertura baixa"
+            exit 1
+          fi
